name: Build and publish image to dockerhub
on: 
  [workflow_dispatch]

jobs: 
    publish_image:
      runs-on: ubuntu-latest
      steps: 
        - name: checkout
          uses: actions/checkout/@v4
        - name: build image
          run: docker build -t mohamedzeidd/docker-project:latest .
        - name: push image to dockerhub
          run: 
            docker push mohamedzeidd/Docker-Project:latest